# Generated by Django 5.0.2 on 2024-02-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
